name: Sample Build

on:
  push:
    branches-ignore:
      - main

env:
  productNamespacePrefix: "Sextant"

jobs:
  build:
    permissions:
      contents: read
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      productNamespacePrefix: "Sextant"
      dotNetBuild: true
      srcFolder: "src/Sample"
      solutionFile: "SextantSample.slnx"
