name: Release

on:
  push:
    branches:
      - main
      - patches/*
    
env:
  productNamespacePrefix: "Sextant"

jobs:
  release:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-release.yml@main
    with:
      configuration: Release
      productNamespacePrefix: "Sextant"
      useVisualStudioPreview: true
      useMauiCheckDotNetTool: false
      solutionFile: "Sextant.sln"
    secrets:
      SIGN_CLIENT_USER_ID: ${{ secrets.SIGN_CLIENT_USER_ID }}
      SIGN_CLIENT_SECRET: ${{ secrets.SIGN_CLIENT_SECRET }}
      SIGN_CLIENT_CONFIG: ${{ secrets.SIGN_CLIENT_CONFIG }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}